# Generated by Django 5.2.5 on 2025-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_patient_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
