# Generated by Django 5.2.5 on 2025-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0004_alter_appointment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
