# Generated by Django 5.2.4 on 2025-08-14 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_remove_token_created_at_medicine_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
