# Generated by Django 5.2.5 on 2025-09-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_alter_appointment_doctor_delete_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
