# Generated by Django 5.2.5 on 2025-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
