# Generated by Django 5.2.4 on 2025-08-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_citizen_token_delete_pharmacytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='citizen',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='dispensed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='token',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='token',
            name='payment_verified',
        ),
        migrations.RemoveField(
            model_name='token',
            name='token_id',
        ),
        migrations.AddField(
            model_name='token',
            name='qr_code',
            field=models.CharField(default=False, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='medicine',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='patient',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Citizen',
        ),
    ]
