# Generated by Django 5.2.6 on 2025-09-17 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='max_tokens_per_slot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'appointment_time', 'token_number')},
        ),
    ]
