# Generated by Django 5.2.6 on 2025-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_appointment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(),
        ),
    ]
