# Generated by Django 5.2.4 on 2025-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pharmacytoken',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='pharmacytoken',
            name='issued_at',
        ),
        migrations.AddField(
            model_name='pharmacytoken',
            name='medicines',
            field=models.TextField(default='paracetamol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacytoken',
            name='patient_name',
            field=models.CharField(default='paracetamol 500mg', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacytoken',
            name='token_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
