# Generated by Django 5.2.4 on 2025-08-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_prescription_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=50, unique=True)),
                ('medicines', models.TextField(blank=True, null=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('dispensed', models.BooleanField(default=False)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.citizen')),
            ],
        ),
        migrations.DeleteModel(
            name='PharmacyToken',
        ),
    ]
