# Generated by Django 5.2.5 on 2025-09-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
