# Generated by Django 5.2.5 on 2025-09-30 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('receptionist', '0006_alter_appointment_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receptionist.patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicinemaster',
            name='default_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='custom_medicine',
            field=models.CharField(blank=True, help_text='If the doctor types a medicine manually', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, help_text='Dosage, e.g., 1 tablet, 5 ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Number of days to take the medicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, help_text='Frequency, e.g., once a day, twice a day', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(blank=True, help_text='Select medicine from master list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.medicinemaster'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='symptom',
            field=models.CharField(blank=True, help_text='Symptom or condition this medicine is for', max_length=200, null=True),
        ),
    ]
