# Generated by Django 5.2.5 on 2025-09-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_consultation_patient_id_consultation_patient_and_more'),
        ('receptionist', '0006_alter_appointment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='receptionist.patient'),
        ),
    ]
