# Generated by Django 5.2.5 on 2025-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_consultation_doctor_alter_consultation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
