# Generated by Django 5.2.4 on 2025-09-18 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='prescription',
        ),
        migrations.AddField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patient'),
        ),
        migrations.AlterField(
            model_name='token',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(max_length=50),
        ),
    ]
