# Generated by Django 5.2.4 on 2025-09-18 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_token_prescription_token_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
    ]
