# Generated by Django 5.2.4 on 2025-09-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicine_created_at_medicine_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicines',
        ),
    ]
