# Generated by Django 5.2.4 on 2025-10-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='frequency',
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
