# Generated by Django 5.2.4 on 2025-10-02 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_remove_medicine_frequency_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.doctor'),
        ),
        migrations.AlterField(
            model_name='token',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tokens/'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
