# Generated by Django 5.2.5 on 2025-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_consultation_follow_up_consultation_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of the medicine per unit', max_digits=10),
        ),
    ]
