# Generated by Django 5.2.5 on 2025-09-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_alter_appointment_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
