# Generated by Django 5.2.4 on 2025-08-14 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_medicine_created_at_patient_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='created_at',
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='qr_code',
            field=models.ImageField(blank=True, default='default_qr.png', upload_to='qr_codes'),
            preserve_default=False,
        ),
    ]
