# Generated by Django 5.2.4 on 2025-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_medicine_stock_alter_medicine_name_pharmacyorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pharmacyorderitem',
            name='medicine',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='price',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='strength',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(default='Unknown Doctor', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PharmacyOrder',
        ),
        migrations.DeleteModel(
            name='PharmacyOrderItem',
        ),
    ]
