# Generated by Django 5.2.4 on 2025-09-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_remove_pharmacyorderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='mg_per_day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
