# Generated by Django 5.2.4 on 2025-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_prescriptionitem_days_prescriptionitem_mg_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mg',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
